version: "3.9"

services: 
#  nginx:
#    image: nginx
#    volumes:
#      - ./nginx/nginx.conf:/tmp/nginx.conf
#    restart: unless-stopped
#    env_file:
#      - .env
#    ports:
#      - '80:80'
#    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
#    depends_on:
#      - frontend
#      - backend
#  backend:
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
  frontend: 
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:3000'
