version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'

  nextjs:
    container_name: nextjs
    build: 
      context: ./frontend
      dockerfile: Dockerfile

  nginx:
    build: ./nginx
    ports:
      - 80:80
