version: "3.9"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - '80:80'
    env_file: .env
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock'
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
